version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    env_file:
      - .env
    ports:
      - "3307:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    container_name: backend-app
    restart: always
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: frontend-app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
